const auth = '/auth'

export enum RouteEnum {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  CREATE_PASSWORD = '/create-password',
  FORGOT_PASSWORD = '/forgot-password',
  PUBLIC_ATHLETE = '/athlete',
  AUTHENTICATED = '/auth',
  ATHLETES = `${auth}/athletes`,
  CREATE_ATHLETE = `${auth}/athletes/create`,
  ATHLETE_ID = `${auth}/athletes/:ID/`,
  DETAIL_ATHLETE = `${auth}/athletes/:ID/info`,
  UPDATE_ATHLETE = `${auth}/athletes/:ID/info/update`,
  MONITORY = `${auth}/athletes/:ID/monitoring`,
  TRAININGS = `${auth}/athletes/:ID/training`,
  CREATE_TRAINING = `${auth}/athletes/:ID/training/create`,
  UPDATE_TRAINING = `${auth}/athletes/:ID/training/:CHILD_ID/update`,
  TRAINING_PLANNING = `${auth}/athletes/:ID/training-planning`,
  CREATE_TRAINING_PLANNING = `${auth}/athletes/:ID/training-planning/create`,
  UPDATE_TRAINING_PLANNING = `${auth}/athletes/:ID/training-planning/:CHILD_ID/update`,
  INJURIES = `${auth}/athletes/:ID/injuries`,
  INJURY_DETAIL = `${auth}/athletes/:ID/injuries/:CHILD_ID`,
  CREATE_INJURY = `${auth}/athletes/:ID/injuries/create`,
  UPDATE_INJURY = `${auth}/athletes/:ID/injuries/:CHILD_ID/update`,
  PAINS = `${auth}/athletes/:ID/pains`,
  PAIN_DETAIL = `${auth}/athletes/:ID/pains/:CHILD_ID`,
  CREATE_PAIN = `${auth}/athletes/:ID/pains/create`,
  UPDATE_PAIN = `${auth}/athletes/:ID/pains/:CHILD_ID/update`,
  TEAM_MEMBERS = `${auth}/team-members`,
  CREATE_TEAM_MEMBERS = `${auth}/team-members/create`,
  UPDATE_TEAM_MEMBERS = `${auth}/team-members/:ID/update`,
  TRAINING_TYPES = `${auth}/training-types`,
  TERMS_OF_USE = '/terms-of-use',
  PRIVACY_POLICY = '/privacy-policy',
  UNSUBSCRIBE = '/unsubscribe/:ID',
}
